/*
  preguntas.js
  Contenido del examen: los 7 temas (TOPICS) y el banco de preguntas (QUESTION_BANK).
  Este archivo NO tiene lógica de la aplicación: solo datos. Para agregar, quitar o editar
  preguntas, este es el único archivo que necesitas tocar (ver README.md para ejemplos
  de cada tipo). Debe cargarse en index.html ANTES de js/app.js, porque app.js usa estas
  dos variables globales.

  Forma de cada pregunta según su "type":
  - mc / vf   : { options:[...], answerIndex } o { answer: true/false }
  - fill      : { answers:[...] } (una o más respuestas válidas, sin acentos/mayúsculas)
  - match     : { pairs:[{l,r}, ...] } (relacionar con listas desplegables)
  - connect   : { pairs:[{l,r}, ...] } (relacionar tocando: izquierda y luego derecha)
  - diagram   : { diagramKind:'triangle'|'layers', slots:[{key,label,correct}], pool:[...] }
  - open      : { model } (respuesta modelo; el usuario se autoevalúa)

  Esta edición cubre Bases de Datos de forma exhaustiva, siguiendo la guía de estudio
  completa: modelo relacional y normalización, DDL/DML (incluido el script SQL aplicado
  gestion_pedidos), consultas multitabla (JOIN), programación sobre datos (SP/Functions/
  Triggers) y, del lado distribuido, fundamentos y arquitecturas de almacenamiento, diseño
  (requerimientos, CAP, ACID/BASE) y consistencia/concurrencia (PACELC, bloqueos, deadlocks,
  2PC). No hay un número fijo de preguntas: el banco crece con la guía, no al revés.
*/

var TOPICS = [
  {id:'modelo', name:'Modelo relacional, llaves y normalización', short:'Modelo relacional', color:'--t-cia'},
  {id:'ddldml', name:'DDL, DML y SQL aplicado', short:'DDL y DML', color:'--t-avr'},
  {id:'joins', name:'Consultas multitabla (JOIN)', short:'JOIN', color:'--t-ia'},
  {id:'progdatos', name:'Programación sobre datos: SP, Functions y Triggers', short:'Programación', color:'--t-hackers'},
  {id:'arquitecturas', name:'Bases de datos distribuidas: fundamentos y arquitecturas', short:'BD distribuidas', color:'--t-leyes'},
  {id:'diseno', name:'Diseño distribuido: requerimientos, CAP y ACID/BASE', short:'Diseño y CAP', color:'--t-eh'},
  {id:'consistencia', name:'Consistencia, concurrencia y 2PC', short:'Consistencia', color:'--t-defensa'}
];

var QUESTION_BANK = [
  // ---------- Modelo relacional, llaves y normalización (24) ----------
  {id:'q1', topic:'modelo', type:'vf',
    prompt:'Edgar F. Codd propuso el modelo relacional en 1970, organizando los datos en tablas formadas por tuplas (renglones) y atributos (columnas).',
    answer:true,
    explain:'Codd publicó "A Relational Model of Data for Large Shared Data Banks" en 1970; es la base teórica de MySQL, PostgreSQL, Oracle y SQL Server.'},
  {id:'q2', topic:'modelo', type:'fill',
    prompt:'En una tabla relacional, el número total de atributos (columnas) de una relación se llama ___ de la relación.',
    answers:['grado'],
    explain:'Grado = número de atributos. Por ejemplo, una tabla clientes con id_cliente, nombre, correo y ciudad tiene grado 4.'},
  {id:'q3', topic:'modelo', type:'fill',
    prompt:'En el modelo relacional, cada renglón (fila) de una tabla se llama una ___.',
    answers:['tupla'],
    explain:'Tupla = cada renglón; atributo = cada columna; grado = número de atributos.'},
  {id:'q4', topic:'modelo', type:'connect',
    prompt:'Conecta cada entidad del caso "tienda" con sus atributos principales.',
    pairs:[
      {l:'Cliente', r:'id_cliente, nombre, correo, ciudad'},
      {l:'Pedido', r:'id_pedido, fecha_pedido, estado'},
      {l:'Categoría', r:'id_categoria, nombre'},
      {l:'Producto', r:'id_producto, nombre, precio, stock'},
      {l:'Pago', r:'id_pago, monto, método, fecha_pago'}
    ],
    explain:'Una entidad es un objeto o concepto del negocio del cual guardamos información; cada una se modela como una tabla con sus propios atributos.'},
  {id:'q5', topic:'modelo', type:'vf',
    prompt:'En SQL, una relación 1:N se implementa colocando la llave foránea en la tabla del lado "N".',
    answer:true,
    explain:'Por ejemplo, en la relación Cliente (1) - Pedido (N), la llave foránea id_cliente vive en la tabla pedidos.'},
  {id:'q6', topic:'modelo', type:'vf',
    prompt:'Una relación N:M puede implementarse con una llave foránea directa entre las dos tablas, sin necesidad de una tabla intermedia.',
    answer:false,
    explain:'El modelo relacional no permite llaves foráneas "de muchos a muchos" directas; se resuelve con una tabla intermedia (asociativa) con una FK hacia cada entidad.'},
  {id:'q7', topic:'modelo', type:'connect',
    prompt:'Conecta cada cardinalidad con dónde vive la llave foránea en el esquema de la tienda.',
    pairs:[
      {l:'1:1 (Pedido y Pago)', r:'La llave foránea va en la tabla "pagos", con una restricción UNIQUE sobre id_pedido.'},
      {l:'1:N (Cliente y Pedidos)', r:'La llave foránea va en el lado "N": en la tabla "pedidos" (columna id_cliente).'},
      {l:'1:N (Categoría y Productos)', r:'La llave foránea va en "productos" (columna id_categoria).'},
      {l:'N:M (Pedidos y Productos)', r:'Se resuelve con una tabla intermedia, "detalle_pedido", que guarda ambas llaves foráneas.'}
    ],
    explain:'La llave foránea siempre vive del lado "N"; una relación N:M necesita una tabla asociativa.'},
  {id:'q8', topic:'modelo', type:'fill',
    prompt:'En el caso de la tienda, el cliente 1 (Marisol Hernández) aparece en los pedidos 1001 y 1003: eso es el lado ___ de la relación 1:N Cliente-Pedidos.',
    answers:['n'],
    explain:'El cliente 2 (Jorge Ramírez) solo tiene el pedido 1002; Marisol, en cambio, tiene varios pedidos, que es justamente el lado "N".'},
  {id:'q9', topic:'modelo', type:'connect',
    prompt:'Conecta cada restricción (constraint) del modelo relacional con lo que garantiza.',
    pairs:[
      {l:'NOT NULL', r:'El atributo siempre debe tener un valor.'},
      {l:'UNIQUE', r:'No se repiten valores en ese atributo (aunque sí puede haber un NULL).'},
      {l:'CHECK', r:'Valida una condición lógica, por ejemplo que el precio sea mayor que 0.'},
      {l:'DEFAULT', r:'Valor que toma la columna si no se especifica uno al insertar.'},
      {l:'PRIMARY KEY', r:'Identifica de forma única cada renglón; no admite NULL ni valores repetidos.'},
      {l:'FOREIGN KEY', r:'El valor debe existir como llave primaria en la tabla referenciada.'}
    ],
    explain:'Estas seis restricciones se declaran al crear la tabla y el motor de base de datos las hace cumplir en cada operación.'},
  {id:'q10', topic:'modelo', type:'fill',
    prompt:'La llave candidata que se elige para identificar oficialmente cada renglón de una tabla se llama llave ___.',
    answers:['primaria'],
    explain:'Debe ser única, nunca nula (NOT NULL implícito) e idealmente estable en el tiempo; puede ser simple o compuesta.'},
  {id:'q11', topic:'modelo', type:'fill',
    prompt:'Una llave candidata debe cumplir dos propiedades: unicidad (no se repite) y ___ (no se puede quitar ningún atributo sin perder la unicidad).',
    answers:['minimalidad'],
    explain:'Por ejemplo, id_cliente y correo son llaves candidatas (ambas únicas); nombre no lo es, porque dos clientes distintos podrían llamarse igual.'},
  {id:'q12', topic:'modelo', type:'vf',
    prompt:'Una llave foránea (foreign key) puede admitir valores NULL cuando la relación que representa es opcional.',
    answer:true,
    explain:'Puede repetirse dentro de su tabla (el lado "N" de una relación 1:N) y puede admitir NULL si la relación es opcional.'},
  {id:'q13', topic:'modelo', type:'vf',
    prompt:'Una tabla puede tener más de una llave primaria a la vez, una por cada llave candidata que tenga.',
    answer:false,
    explain:'Cada tabla tiene exactamente una llave primaria (que puede estar formada por varios atributos: llave compuesta); las demás llaves candidatas simplemente no se eligen.'},
  {id:'q14', topic:'modelo', type:'connect',
    prompt:'Conecta cada tipo de integridad de datos con lo que protege.',
    pairs:[
      {l:'Integridad de entidad', r:'Que la llave primaria sea única y nunca nula, para que cada renglón sea identificable.'},
      {l:'Integridad referencial', r:'Que toda llave foránea corresponda a un valor existente en la tabla referenciada (o sea NULL si se permite).'},
      {l:'Integridad de dominio', r:'Que cada valor respete el tipo de dato y las reglas del atributo (rango, formato, lista permitida).'}
    ],
    explain:'Las tres se configuran declarativamente con PRIMARY KEY, FOREIGN KEY, tipos de dato y CHECK, y el motor las hace cumplir en cada operación.'},
  {id:'q15', topic:'modelo', type:'connect',
    prompt:'Conecta cada violación con el tipo de integridad que rompe.',
    pairs:[
      {l:'INSERT con un id_producto repetido (Error 1062, "Duplicate entry")', r:'Viola integridad de entidad: la llave primaria debe ser única.'},
      {l:'INSERT con id_cliente = 999, que no existe en clientes (Error 1452)', r:'Viola integridad referencial: la llave foránea debe existir en la tabla referenciada.'},
      {l:'DELETE de un cliente con pedidos, con la FK en RESTRICT (Error 1451)', r:'Viola integridad referencial: no se puede borrar un "padre" mientras existan "hijos" que lo referencian.'},
      {l:"INSERT con precio = 'gratis' en una columna numérica (Error 1366)", r:'Viola integridad de dominio: el valor no respeta el tipo de dato de la columna.'},
      {l:'INSERT con precio = -50.00, violando un CHECK (Error 3819)', r:'Viola integridad de dominio: el valor no cumple la regla de negocio declarada con CHECK.'}
    ],
    explain:'En la práctica, un error de "foreign key", "duplicate entry" o "check constraint" casi siempre es una de estas tres reglas protegiendo la consistencia.'},
  {id:'q16', topic:'modelo', type:'open',
    prompt:'Explica la diferencia entre integridad de entidad, integridad referencial e integridad de dominio, y da un ejemplo de violación de cada una.',
    model:'Integridad de entidad: la llave primaria debe ser única y nunca nula (ej. insertar dos productos con el mismo id_producto). Integridad referencial: toda llave foránea debe existir como llave primaria en la tabla referenciada, o ser NULL si se permite (ej. un pedido con un id_cliente que no existe). Integridad de dominio: cada valor debe respetar el tipo de dato y las reglas del atributo (ej. un precio negativo o un texto en un campo numérico). Las tres se declaran con PRIMARY KEY, FOREIGN KEY, tipos de dato y CHECK, y el motor las hace cumplir en cada operación.'},
  {id:'q17', topic:'modelo', type:'connect',
    prompt:'Conecta cada anomalía de las tablas sin normalizar con su ejemplo en el caso de la tienda.',
    pairs:[
      {l:'Anomalía de inserción', r:'No se puede dar de alta el producto "P006: Webcam HD" en el catálogo si todavía no aparece en ningún pedido.'},
      {l:'Anomalía de actualización', r:'Si Marisol Hernández se muda de Guadalajara a Puebla, hay que corregir "ciudad_cliente" en todas sus filas; si se olvida una, quedan datos contradictorios.'},
      {l:'Anomalía de eliminación', r:'Si se cancela y se borra el único pedido de Jorge Ramírez, se pierde también el único registro de que es cliente de Monterrey.'}
    ],
    explain:'Las tres anomalías son consecuencia de la redundancia en una tabla sin normalizar; la normalización busca reducirlas.'},
  {id:'q18', topic:'modelo', type:'vf',
    prompt:'Una tabla está en Primera Forma Normal (1FN) si alguna de sus columnas guarda listas de valores separadas por comas o por el carácter "|".',
    answer:false,
    explain:'Justo lo contrario: eso viola la 1FN (rompe la atomicidad). Para cumplirla, cada celda debe tener un solo valor, y las listas deben separarse en renglones o en una tabla propia.'},
  {id:'q19', topic:'modelo', type:'fill',
    prompt:'Al aplicar la 1FN a la tabla "pedidos_bruto" (donde la columna productos guardaba listas separadas por "|"), la llave primaria de la tabla resultante ("pedidos_1fn") es la combinación de id_pedido e id____.',
    answers:['producto'],
    explain:'Cada producto de un pedido ahora ocupa su propio renglón, así que la llave mínima que identifica cada fila es (id_pedido, id_producto).'},
  {id:'q20', topic:'modelo', type:'vf',
    prompt:'La Segunda Forma Normal (2FN) solo aplica cuando la llave primaria de la tabla es compuesta (tiene más de un atributo).',
    answer:true,
    explain:'Se viola con una "dependencia parcial": un atributo que depende solo de una parte de la llave compuesta, no de la llave completa.'},
  {id:'q21', topic:'modelo', type:'connect',
    prompt:'Conecta cada tabla resultante de aplicar la 2FN con lo que contiene.',
    pairs:[
      {l:'pedidos_2fn', r:'id_pedido (PK), fecha_pedido, id_cliente, nombre_cliente, ciudad_cliente.'},
      {l:'productos_2fn', r:'id_producto (PK), nombre_producto.'},
      {l:'detalle_2fn', r:'id_pedido, id_producto, cantidad; PK compuesta (id_pedido, id_producto).'}
    ],
    explain:'Se separan los atributos que dependían solo de id_producto o solo de id_pedido, pero "pedidos_2fn" todavía mezcla datos del pedido con datos del cliente: falta la 3FN.'},
  {id:'q22', topic:'modelo', type:'fill',
    prompt:'Cuando una tabla en 2FN todavía tiene un atributo que depende de otro atributo que no es llave (por ejemplo, el nombre del cliente depende de id_cliente, que a su vez depende de id_pedido), se dice que existe una dependencia ___, y hace falta llevar la tabla a Tercera Forma Normal.',
    answers:['transitiva'],
    explain:'Dependencia transitiva: A -> B -> C. La solución es mover esos atributos a su propia tabla (ej. "clientes") y dejar solo la llave foránea.'},
  {id:'q23', topic:'modelo', type:'fill',
    prompt:'El esquema final normalizado en 3FN (clientes, productos, pedidos y detalle_pedido) tiene ___ tablas.',
    answers:['4','cuatro'],
    explain:'Sin normalizar: 1 tabla. 1FN: 1 tabla. 2FN: 3 tablas. 3FN: 4 tablas, cada una describiendo una sola entidad o relación.'},
  {id:'q24', topic:'modelo', type:'open',
    prompt:'Usando el ejemplo de "pedidos_bruto" (con la columna productos separada por "|"), explica los cuatro pasos del camino de una tabla sin normalizar hasta la Tercera Forma Normal (3FN).',
    model:'Sin normalizar: 1 tabla, con la columna "productos" guardando varios valores separados por "|" (viola 1FN). 1FN: 1 tabla ("pedidos_1fn"), cada producto de un pedido ocupa su propio renglón, con llave compuesta (id_pedido, id_producto); pero se repite mucho el nombre del cliente y del producto. 2FN: 3 tablas, separando los atributos que dependían solo de id_producto (productos_2fn) o solo de id_pedido (pedidos_2fn), y dejando la cantidad en una tabla de detalle. 3FN: 4 tablas, separando además los atributos del cliente (nombre, ciudad) que dependían transitivamente de id_pedido a través de id_cliente, y moviéndolos a su propia tabla "clientes".'},

  // ---------- DDL, DML y SQL aplicado (24) ----------
  {id:'q25', topic:'ddldml', type:'fill',
    prompt:'SQL se divide en cuatro sub-lenguajes: DDL, DML, DCL y ___ (control de transacciones).',
    answers:['tcl'],
    explain:'DDL (CREATE/ALTER/DROP/TRUNCATE), DML (INSERT/SELECT/UPDATE/DELETE), DCL (GRANT/REVOKE) y TCL (COMMIT/ROLLBACK/SAVEPOINT).'},
  {id:'q26', topic:'ddldml', type:'connect',
    prompt:'Conecta cada sub-lenguaje de SQL con sus comandos.',
    pairs:[
      {l:'DDL (Definición de datos)', r:'CREATE · ALTER · DROP · TRUNCATE'},
      {l:'DML (Manipulación de datos)', r:'INSERT · SELECT · UPDATE · DELETE'},
      {l:'DCL (Control de datos)', r:'GRANT · REVOKE'},
      {l:'TCL (Control de transacciones)', r:'COMMIT · ROLLBACK · SAVEPOINT'}
    ],
    explain:'DDL define el contenedor (bases de datos, tablas, columnas); DML opera sobre el contenido (filas).'},
  {id:'q27', topic:'ddldml', type:'fill',
    prompt:'El tipo equivalente a "INT AUTO_INCREMENT" de MySQL en PostgreSQL es SERIAL, o también GENERATED ... ___.',
    answers:['identity'],
    explain:'Ambos son formas de declarar un entero autoincremental como llave primaria.'},
  {id:'q28', topic:'ddldml', type:'connect',
    prompt:'Conecta cada tipo de dato con su equivalente en MySQL y PostgreSQL.',
    pairs:[
      {l:'Entero autoincremental', r:'MySQL: INT AUTO_INCREMENT · PostgreSQL: SERIAL / GENERATED...IDENTITY'},
      {l:'Decimal exacto (dinero)', r:'MySQL: DECIMAL(p,s) · PostgreSQL: NUMERIC(p,s)'},
      {l:'Fecha y hora', r:'MySQL: DATETIME · PostgreSQL: TIMESTAMP'},
      {l:'Verdadero / falso', r:'MySQL: TINYINT(1) o BOOLEAN · PostgreSQL: BOOLEAN'}
    ],
    explain:'CREATE TABLE define columnas, tipos de dato y restricciones; los nombres de los tipos varían un poco entre motores.'},
  {id:'q29', topic:'ddldml', type:'vf',
    prompt:'Se debe crear primero la tabla "padre" (por ejemplo, autores) antes que la tabla "hija" (libros), porque una tabla no puede referenciar a otra que aún no existe.',
    answer:true,
    explain:'La tabla libros tiene una llave foránea hacia autores(id_autor); si autores no existe todavía, el CREATE TABLE de libros fallaría.'},
  {id:'q30', topic:'ddldml', type:'connect',
    prompt:'Conecta cada operación de ALTER TABLE con su instrucción.',
    pairs:[
      {l:'Agregar columna', r:'ADD COLUMN'},
      {l:'Cambiar tipo de dato', r:'MODIFY / ALTER COLUMN'},
      {l:'Renombrar columna', r:'RENAME COLUMN'},
      {l:'Eliminar columna', r:'DROP COLUMN'}
    ],
    explain:'Cuando la tabla ya tiene datos, no se borra y se vuelve a crear: se modifica con ALTER TABLE.'},
  {id:'q31', topic:'ddldml', type:'connect',
    prompt:'Conecta cada instrucción con lo que realmente elimina y si se puede deshacer.',
    pairs:[
      {l:'DROP TABLE', r:'Elimina la tabla completa (estructura y datos); no se puede deshacer y no aplica reinicio de autoincremento.'},
      {l:'TRUNCATE TABLE', r:'Elimina todas las filas pero conserva la estructura; es DDL (no se deshace) y sí reinicia el autoincremento.'},
      {l:'DELETE (DML)', r:'Elimina las filas seleccionadas (o todas), conservando la estructura; sí se puede deshacer con ROLLBACK antes del COMMIT.'}
    ],
    explain:'DROP y TRUNCATE no piden confirmación y casi nunca se pueden revertir; por eso conviene respaldar antes de ejecutarlos en producción.'},
  {id:'q32', topic:'ddldml', type:'vf',
    prompt:'DDL hace un commit implícito, por lo que un cambio de estructura no se puede revertir con ROLLBACK como sí ocurre con DML.',
    answer:true,
    explain:'Por eso un DROP TABLE mal ejecutado es uno de los errores más costosos en producción: no hay vuelta atrás.'},
  {id:'q33', topic:'ddldml', type:'fill',
    prompt:'La restricción ___ garantiza que una columna nunca tenga valores repetidos, aunque sí puede admitir un NULL.',
    answers:['unique'],
    explain:'A diferencia de PRIMARY KEY (que no admite NULL ni repetidos), UNIQUE solo prohíbe los valores repetidos.'},
  {id:'q34', topic:'ddldml', type:'connect',
    prompt:'Conecta cada operación de DDL con su equivalente en MySQL y en PostgreSQL.',
    pairs:[
      {l:'Autoincremento', r:'MySQL: AUTO_INCREMENT · PostgreSQL: SERIAL / GENERATED...IDENTITY'},
      {l:'Cambiar tipo de columna', r:'MySQL: MODIFY COLUMN · PostgreSQL: ALTER COLUMN ... TYPE'},
      {l:'Cambiar de base de datos', r:"MySQL: USE nombre_bd; · PostgreSQL: nueva conexión (\\c nombre_bd)"},
      {l:'Comentario de una línea', r:'MySQL: -- texto ó # texto · PostgreSQL: -- texto'}
    ],
    explain:'Las ideas de DDL son las mismas en ambos motores, aunque la sintaxis exacta cambia un poco.'},
  {id:'q35', topic:'ddldml', type:'fill',
    prompt:'En el acrónimo CRUD de DML, la letra R corresponde a "Read", que en SQL se traduce en la instrucción ___.',
    answers:['select'],
    explain:'Create = INSERT, Read = SELECT, Update = UPDATE, Delete = DELETE.'},
  {id:'q36', topic:'ddldml', type:'vf',
    prompt:'A diferencia de DDL, en DML sí se puede revertir con ROLLBACK antes del COMMIT.',
    answer:true,
    explain:'DML opera sobre el contenido (filas) y admite transacciones; DDL, en general, no.'},
  {id:'q37', topic:'ddldml', type:'fill',
    prompt:'En PostgreSQL, para recuperar el id recién generado en la misma sentencia de INSERT se usa la cláusula ___.',
    answers:['returning'],
    explain:"Ejemplo: INSERT INTO autores (nombre) VALUES ('Julio Cortázar') RETURNING id_autor;"},
  {id:'q38', topic:'ddldml', type:'fill',
    prompt:'Antes de ejecutar un UPDATE o DELETE sin estar seguro de qué filas afectará, la buena práctica es correr primero un ___ con la misma condición del WHERE.',
    answers:['select'],
    explain:'Así confirmas exactamente qué filas se van a afectar antes de modificarlas o borrarlas de verdad.'},
  {id:'q39', topic:'ddldml', type:'connect',
    prompt:'Conecta cada error frecuente de SQL con su causa y su forma de evitarlo.',
    pairs:[
      {l:'UPDATE / DELETE sin WHERE', r:'Se modifica o borra toda la tabla; prueba primero el WHERE como un SELECT.'},
      {l:'Confundir DROP con TRUNCATE', r:'DROP también elimina la estructura; revisa la tabla comparativa antes de ejecutar.'},
      {l:'Crear la tabla "hija" antes que la "padre"', r:'Produce un error de llave foránea; diseña el diagrama y crea las tablas en orden de dependencia.'},
      {l:'Suponer que DDL admite ROLLBACK', r:'El cambio de estructura queda permanente; prueba los cambios en un ambiente de desarrollo.'}
    ],
    explain:'Estos cuatro son los errores más comunes al mezclar DDL y DML sin cuidado.'},
  {id:'q40', topic:'ddldml', type:'open',
    prompt:'¿Por qué siempre se enseña y se ejecuta primero el DDL y después el DML? Explica qué pasaría si se intentara al revés.',
    model:'Porque DDL define el contenedor (bases de datos, tablas, columnas) y DML opera sobre el contenido de ese contenedor (filas). No se puede insertar, leer, actualizar ni borrar datos en una tabla que todavía no existe, así que intentar DML antes que DDL simplemente fallaría: el motor no encontraría la tabla o columna referenciada.'},
  {id:'q41', topic:'ddldml', type:'vf',
    prompt:'En el esquema gestion_pedidos (del script SQL de ejemplo), la tabla Pedido_Productos usa una llave primaria compuesta por IdPedido e IdProducto.',
    answer:true,
    explain:'PRIMARY KEY (IdPedido, IdProducto): es la combinación mínima que identifica cada renglón de esa tabla intermedia.'},
  {id:'q42', topic:'ddldml', type:'fill',
    prompt:'En el esquema gestion_pedidos, la llave foránea de Pedido_Productos hacia Pedido usa ON DELETE ___: si se borra un pedido, sus filas en Pedido_Productos se eliminan automáticamente.',
    answers:['cascade'],
    explain:'A diferencia de las FK hacia Cliente y Repartidos en la tabla Pedido, que usan ON DELETE SET NULL.'},
  {id:'q43', topic:'ddldml', type:'connect',
    prompt:'Conecta cada tabla del esquema gestion_pedidos con su llave primaria.',
    pairs:[
      {l:'Cliente', r:'IdCliente'},
      {l:'Tienda', r:'TiendaID'},
      {l:'Repartidos', r:'RepartidorID'},
      {l:'Productos', r:'IdProducto'},
      {l:'Pedido_Productos', r:'(IdPedido, IdProducto) — llave compuesta'}
    ],
    explain:'Cada tabla del esquema gestion_pedidos tiene su propia llave primaria, simple o compuesta.'},
  {id:'q44', topic:'ddldml', type:'fill',
    prompt:'En el script de ejemplo, la consulta "SELECT ... FROM Productos WHERE Precio > 500" regresa un solo producto: el ___ Mecánico (sin acentos).',
    answers:['teclado'],
    explain:'Solo el Teclado Mecánico (precio 1200) supera los 500; Soporte Laptop (450) y Mouse Pad (250) no cumplen el filtro.'},
  {id:'q45', topic:'ddldml', type:'fill',
    prompt:'En la consulta con GROUP BY sobre Cliente y Pedido del script gestion_pedidos, Carlos Perez aparece con 1 pedido y un total gastado de ___.',
    answers:['700'],
    explain:'Ana Gomez aparece con 1 pedido y 1200 de total gastado; Carlos Perez con 1 pedido y 700.'},
  {id:'q46', topic:'ddldml', type:'vf',
    prompt:'En el esquema gestion_pedidos, la tabla Productos tiene una llave foránea hacia Tienda con ON DELETE SET NULL: si se borra la tienda, el producto conserva su registro pero con TiendaID vacío.',
    answer:true,
    explain:'Así se declara: CONSTRAINT fk_productos_tienda FOREIGN KEY (TiendaID) REFERENCES Tienda(TiendaID) ON DELETE SET NULL.'},
  {id:'q47', topic:'ddldml', type:'vf',
    prompt:'En el script gestion_pedidos, la tabla Pedido tiene dos llaves foráneas: una hacia Cliente y otra hacia Repartidos.',
    answer:true,
    explain:'IdCliente referencia a Cliente(IdCliente) y RepartidosRepartidorID referencia a Repartidos(RepartidorID), ambas con ON DELETE SET NULL.'},
  {id:'q48', topic:'ddldml', type:'open',
    prompt:'En el script gestion_pedidos, explica qué hace la consulta con JOIN, GROUP BY y HAVING sobre Tienda, Productos y Pedido_Productos, y qué representa su resultado.',
    model:'La consulta une Tienda con Productos (por TiendaID) y Productos con Pedido_Productos (por IdProducto), agrupa por tienda (GROUP BY t.TiendaID, t.Nombre) y suma el Subtotal de cada línea vendida (SUM(pp.Subtotal)) para obtener los ingresos totales por tienda. La cláusula HAVING SUM(pp.Subtotal) > 1000 filtra el resultado ya agregado, dejando solo las tiendas cuyos ingresos totales superan 1000, algo que WHERE no podría hacer porque WHERE filtra filas antes de agrupar, no el resultado de una función de agregación.'},

  // ---------- Consultas multitabla (JOIN) (14) ----------
  {id:'q49', topic:'joins', type:'fill',
    prompt:'En el esquema de biblioteca, la cadena de relaciones 1:N es: autores -> libros -> ___ -> socios.',
    answers:['prestamos'],
    explain:'autores -1:N- libros -1:N- prestamos -1:N- socios.'},
  {id:'q50', topic:'joins', type:'connect',
    prompt:'Conecta cada tipo de JOIN con lo que conserva de las tablas A y B.',
    pairs:[
      {l:'INNER JOIN', r:'Devuelve solo las filas donde la condición de unión se cumple en ambas tablas.'},
      {l:'LEFT JOIN', r:'Devuelve todas las filas de la tabla izquierda, tengan o no coincidencia; sin coincidencia, la derecha se rellena con NULL.'},
      {l:'RIGHT JOIN', r:'Es el espejo del LEFT JOIN: devuelve todas las filas de la tabla derecha, tengan o no coincidencia.'},
      {l:'FULL OUTER JOIN', r:'Conserva las filas de ambas tablas, tengan o no coincidencia del otro lado.'},
      {l:'CROSS JOIN', r:'Combina cada fila de una tabla con cada fila de la otra, sin condición de coincidencia (producto cartesiano).'}
    ],
    explain:'Cada tipo de JOIN decide qué filas "sobreviven" cuando no hay coincidencia entre las tablas.'},
  {id:'q51', topic:'joins', type:'vf',
    prompt:'MySQL soporta de forma nativa el FULL OUTER JOIN, igual que PostgreSQL.',
    answer:false,
    explain:'PostgreSQL sí lo soporta nativamente; en MySQL hay que simularlo combinando un LEFT JOIN y un RIGHT JOIN con UNION.'},
  {id:'q52', topic:'joins', type:'fill',
    prompt:'Para encontrar los socios que nunca han pedido un préstamo se usa un LEFT JOIN de socios hacia préstamos, filtrando WHERE p.id_prestamo IS ___.',
    answers:['null'],
    explain:'Si no hay coincidencia, las columnas de la tabla de la derecha (préstamos) quedan en NULL; ese filtro aísla a los socios sin préstamos.'},
  {id:'q53', topic:'joins', type:'vf',
    prompt:'Casi cualquier RIGHT JOIN se puede reescribir como un LEFT JOIN invirtiendo el orden de las tablas.',
    answer:true,
    explain:'Por eso en la práctica el RIGHT JOIN se usa poco: el LEFT JOIN invertido es la forma más habitual de escribir la misma consulta.'},
  {id:'q54', topic:'joins', type:'open',
    prompt:'Explica la diferencia entre un INNER JOIN y un LEFT JOIN, usando el ejemplo de libros y préstamos de una biblioteca.',
    model:'Un INNER JOIN entre libros y préstamos devuelve únicamente los libros que sí tienen al menos un préstamo registrado: si un libro nunca se ha prestado, simplemente no aparece en el resultado. Un LEFT JOIN, en cambio, devuelve TODOS los libros (la tabla de la izquierda), tengan o no préstamo; para los libros sin préstamo, las columnas de la tabla de préstamos (fecha_prestamo, etc.) aparecen como NULL.'},
  {id:'q55', topic:'joins', type:'fill',
    prompt:'El JOIN que genera el producto cartesiano entre dos tablas, combinando cada fila de una con cada fila de la otra sin ninguna condición de coincidencia, se llama ___ JOIN.',
    answers:['cross'],
    explain:'Se usa poco en consultas de negocio; su caso típico es generar combinaciones, como una fila por cada par de talla y color.'},
  {id:'q56', topic:'joins', type:'fill',
    prompt:'En la consulta "¿Qué socios nunca han pedido un préstamo?", el resultado del ejemplo es la socia ___ ___.',
    answers:['carla jimenez'],
    explain:'Es el único socio cuyo id_prestamo queda en NULL tras el LEFT JOIN.'},
  {id:'q57', topic:'joins', type:'connect',
    prompt:'Conecta cada combinación de JOIN con lo que representa en el diagrama de Venn de las tablas A y B.',
    pairs:[
      {l:'INNER JOIN', r:'Solo la intersección de A y B.'},
      {l:'LEFT JOIN', r:'Todo el círculo A completo (incluye la intersección con B).'},
      {l:'RIGHT JOIN', r:'Todo el círculo B completo (incluye la intersección con A).'},
      {l:'FULL OUTER JOIN', r:'Ambos círculos completos, A y B.'},
      {l:'LEFT JOIN ... WHERE B IS NULL', r:'Solo la parte de A que NO se traslapa con B.'},
      {l:'RIGHT JOIN ... WHERE A IS NULL', r:'Solo la parte de B que NO se traslapa con A.'}
    ],
    explain:'La región sombreada en cada diagrama de Venn indica exactamente qué filas conserva cada tipo de combinación.'},
  {id:'q58', topic:'joins', type:'vf',
    prompt:'El CROSS JOIN necesita una condición ON para combinar las tablas, igual que un INNER JOIN.',
    answer:false,
    explain:'El CROSS JOIN no usa ninguna condición de coincidencia: combina cada fila de una tabla con cada fila de la otra (producto cartesiano).'},
  {id:'q59', topic:'joins', type:'fill',
    prompt:'Para simular un FULL OUTER JOIN en MySQL se combina un LEFT JOIN y un RIGHT JOIN con la cláusula ___.',
    answers:['union'],
    explain:'PostgreSQL soporta FULL OUTER JOIN de forma nativa; en MySQL hay que unir los dos resultados con UNION.'},
  {id:'q60', topic:'joins', type:'vf',
    prompt:'En un INNER JOIN entre libros y préstamos, un libro que nunca se ha prestado sí aparece en el resultado, con las columnas de préstamo en NULL.',
    answer:false,
    explain:'Eso describe el comportamiento de un LEFT JOIN, no de un INNER JOIN: en INNER JOIN, ese libro simplemente no aparece.'},
  {id:'q61', topic:'joins', type:'open',
    prompt:'Explica qué es un producto cartesiano y da un ejemplo de cuándo tendría sentido usar un CROSS JOIN.',
    model:'Un producto cartesiano combina cada fila de una tabla con cada fila de otra, sin ninguna condición de coincidencia, generando todas las combinaciones posibles. Tiene sentido usarlo, por ejemplo, para generar una fila por cada combinación posible de talla y color de un producto (SELECT t.talla, c.color FROM tallas t CROSS JOIN colores c), en vez de tener que escribir cada combinación a mano.'},
  {id:'q62', topic:'joins', type:'fill',
    prompt:'En un LEFT JOIN, cuando no hay coincidencia en la tabla de la derecha, esas columnas se rellenan con ___.',
    answers:['null'],
    explain:'Es la diferencia clave frente al INNER JOIN, que simplemente descarta esas filas sin coincidencia.'},

  // ---------- Programación sobre datos: SP, Functions y Triggers (14) ----------
  {id:'q63', topic:'progdatos', type:'connect',
    prompt:'Conecta cada concepto de programación sobre datos con su definición.',
    pairs:[
      {l:'Stored Procedure', r:'Conjunto de instrucciones SQL con nombre que se invoca con EXEC o CALL; no siempre regresa un valor y puede modificar datos.'},
      {l:'Function', r:'Rutina que recibe parámetros y SIEMPRE regresa un valor; se puede usar dentro de un SELECT como si fuera una columna.'},
      {l:'Trigger', r:'Bloque de código asociado a una tabla que se ejecuta automáticamente ante un evento (INSERT, UPDATE o DELETE); nadie lo llama directamente.'},
      {l:'inserted', r:'Tabla temporal de un trigger que contiene los valores nuevos del evento.'},
      {l:'deleted', r:'Tabla temporal de un trigger que contiene los valores anteriores del evento.'}
    ],
    explain:'Los tres viven cerca de los datos para reducir viajes de red, dar consistencia y controlar permisos sobre el objeto en lugar de sobre toda la tabla.'},
  {id:'q64', topic:'progdatos', type:'vf',
    prompt:'Una función (function) puede modificar datos con INSERT, UPDATE o DELETE igual que un stored procedure.',
    answer:false,
    explain:'Las funciones no modifican datos; solo calculan y regresan un valor. Modificar datos sin restricción es propio del stored procedure.'},
  {id:'q65', topic:'progdatos', type:'fill',
    prompt:'Un trigger ___ se ejecuta antes de aplicar el cambio (por ejemplo para validar o corregir datos); uno AFTER se ejecuta después (auditoría, notificaciones, cálculos).',
    answers:['before'],
    explain:'BEFORE / INSTEAD OF actúan antes del cambio; AFTER actúa después. Ambos se disparan por evento: INSERT, UPDATE o DELETE.'},
  {id:'q66', topic:'progdatos', type:'vf',
    prompt:'Un stored procedure se puede usar directamente dentro de una cláusula SELECT, igual que una función.',
    answer:false,
    explain:'La función sí se usa dentro de un SELECT como una expresión; el stored procedure se invoca aparte con EXEC/CALL, nunca dentro de un SELECT.'},
  {id:'q67', topic:'progdatos', type:'open',
    prompt:'¿Por qué conviene usar un stored procedure para registrar una venta y descontar el inventario en el mismo paso, en lugar de hacerlo con dos instrucciones sueltas desde la aplicación?',
    model:'Porque ambas operaciones (insertar la venta y actualizar el stock) deben ocurrir juntas o ninguna debe ocurrir: al envolverlas en una transacción dentro del procedimiento, se evita que una app se quede a medias si falla justo entre las dos instrucciones. Además, cualquier aplicación (web, móvil, POS) llama al mismo procedimiento y obtiene siempre el mismo comportamiento, sin duplicar la lógica ni arriesgarse a que alguna app se salte un paso.'},
  {id:'q68', topic:'progdatos', type:'fill',
    prompt:'Las funciones se invocan escribiendo SELECT fn(...), mientras que los stored procedures se invocan con EXEC o ___.',
    answers:['call'],
    explain:'"EXEC" y "CALL" son las dos formas típicas (según el motor) de invocar un stored procedure; nunca se usan dentro de un SELECT.'},
  {id:'q69', topic:'progdatos', type:'fill',
    prompt:'Una función que resume varias filas en un solo valor, como SUM, AVG o COUNT, se llama función ___.',
    answers:['agregada'],
    explain:'Se distingue de la función escalar (devuelve un solo valor por fila) y de la función de tabla (devuelve una tabla completa).'},
  {id:'q70', topic:'progdatos', type:'fill',
    prompt:'Una función que devuelve una tabla completa como resultado, por ejemplo fn_ventas_por_mes(mes), se llama función de ___.',
    answers:['tabla'],
    explain:'Se distingue de la función escalar (un solo valor) y de la función agregada (resume varias filas en un valor).'},
  {id:'q71', topic:'progdatos', type:'vf',
    prompt:'Los stored procedures reciben parámetros de entrada y salida (IN/OUT) y pueden modificar datos con INSERT, UPDATE o DELETE.',
    answer:true,
    explain:'A diferencia de las funciones, que no modifican datos y siempre deben regresar un valor.'},
  {id:'q72', topic:'progdatos', type:'fill',
    prompt:'En el trigger trg_auditar_precio, la tabla temporal ___ contiene los valores nuevos del evento, y "deleted" contiene los valores anteriores.',
    answers:['inserted'],
    explain:'inserted = valores nuevos; deleted = valores anteriores; ambas son tablas temporales que solo existen dentro del trigger.'},
  {id:'q73', topic:'progdatos', type:'vf',
    prompt:'Un trigger se invoca manualmente desde la aplicación con la instrucción EXEC, igual que un stored procedure.',
    answer:false,
    explain:'Nadie llama a un trigger directamente: se dispara solo, de forma automática, cuando ocurre el evento (INSERT, UPDATE o DELETE) sobre su tabla.'},
  {id:'q74', topic:'progdatos', type:'connect',
    prompt:'Conecta cada razón para "programar" dentro de la base de datos con su beneficio.',
    pairs:[
      {l:'Menos viajes de red', r:'La lógica corre en el servidor de datos, no va y viene desde la app.'},
      {l:'Reutilización', r:'Un mismo procedimiento lo llaman muchas aplicaciones o usuarios.'},
      {l:'Consistencia', r:'Las reglas se cumplen sin importar quién escriba en la tabla.'},
      {l:'Seguridad', r:'Se otorgan permisos sobre el objeto (el procedimiento), no sobre la tabla completa.'}
    ],
    explain:'Estos cuatro beneficios son la razón de fondo para usar Stored Procedures, Functions y Triggers.'},
  {id:'q75', topic:'progdatos', type:'fill',
    prompt:'El ejercicio práctico de triggers del material propone crear trg_ajustar_stock, que corrija automáticamente el stock a ___ si un UPDATE lo deja en un número negativo.',
    answers:['0','cero'],
    explain:'En lugar de revertir la operación completa, el trigger corrige el valor resultante.'},
  {id:'q76', topic:'progdatos', type:'open',
    prompt:'¿Qué diferencia hay entre un trigger BEFORE y uno AFTER? Da un ejemplo de uso típico para cada uno.',
    model:'Un trigger BEFORE (o INSTEAD OF) se ejecuta antes de aplicar el cambio, y se usa típicamente para validar o corregir datos antes de que se guarden (por ejemplo, evitar que un stock quede negativo). Un trigger AFTER se ejecuta después de que el cambio ya se aplicó, y se usa para auditoría, notificaciones o cálculos derivados (por ejemplo, registrar en una tabla de auditoría el precio anterior y el nuevo cada vez que se actualiza un producto).'},

  // ---------- Bases de datos distribuidas: fundamentos y arquitecturas (30) ----------
  {id:'q77', topic:'arquitecturas', type:'vf',
    prompt:'En una base de datos distribuida la escalabilidad es horizontal (agregar más nodos), mientras que en una centralizada es vertical (más CPU/RAM al mismo servidor).',
    answer:true,
    explain:'Es una de las diferencias clave: la centralizada crece "hacia arriba" en un solo servidor; la distribuida crece "hacia los lados" agregando nodos.'},
  {id:'q78', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada criterio con la comparación entre base de datos centralizada y distribuida.',
    pairs:[
      {l:'Ubicación física', r:'Centralizada: un solo servidor / sitio. Distribuida: varios nodos, posiblemente en distintas regiones.'},
      {l:'Punto de falla', r:'Centralizada: único, si cae, cae todo. Distribuida: tolerante, con réplicas adecuadas.'},
      {l:'Escalabilidad', r:'Centralizada: vertical (más CPU/RAM). Distribuida: horizontal (agregar más nodos).'},
      {l:'Consistencia', r:'Centralizada: fuerte y simple de garantizar. Distribuida: requiere protocolos (Paxos, Raft, quórums).'},
      {l:'Complejidad operativa', r:'Centralizada: baja. Distribuida: alta (monitoreo, red, coordinación).'}
    ],
    explain:'Ninguna arquitectura es universalmente mejor: la pregunta correcta es cuándo el costo de distribuir se justifica.'},
  {id:'q79', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada ventaja de distribuir una base de datos con su explicación.',
    pairs:[
      {l:'Escalabilidad horizontal', r:'Crecer agregando nodos en lugar de comprar hardware cada vez más caro.'},
      {l:'Alta disponibilidad', r:'Las réplicas permiten seguir operando aunque falle un nodo o una zona completa.'},
      {l:'Menor latencia local', r:'Servir datos desde el nodo geográficamente más cercano al usuario.'},
      {l:'Mayor throughput', r:'Varias consultas se procesan en paralelo en distintos nodos.'},
      {l:'Aislamiento de fallos', r:'Un incidente regional no tiene por qué tumbar todo el sistema.'}
    ],
    explain:'A esto se suma el crecimiento incremental: la infraestructura se amplía por partes, sin migraciones traumáticas.'},
  {id:'q80', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada limitación de las bases de datos distribuidas con su explicación.',
    pairs:[
      {l:'Consistencia difícil', r:'Mantener todos los nodos "de acuerdo" cuesta tiempo y coordinación.'},
      {l:'Teorema CAP', r:'Ante una partición de red hay que elegir entre Consistencia y Disponibilidad.'},
      {l:'Complejidad operativa', r:'Más piezas móviles: red, réplicas, relojes, monitoreo distribuido.'},
      {l:'Costo de coordinación', r:'Los protocolos de consenso (Raft, Paxos) añaden latencia a cada escritura.'},
      {l:'Seguridad ampliada', r:'Más nodos y más red expuesta significan más superficie de ataque.'}
    ],
    explain:'A esto se suma la depuración compleja: un error puede depender del orden de eventos entre nodos distintos.'},
  {id:'q81', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada escenario con la arquitectura que mejor le conviene.',
    pairs:[
      {l:'PyME administrativa (nómina o inventario de una sola sucursal)', r:'Sistema centralizado: pocos usuarios, datos sensibles, simplicidad ante todo.'},
      {l:'E-commerce global', r:'Distribuida: catálogo e inventario replicados por región para servir con baja latencia en cualquier país.'},
      {l:'Sensores IoT / streaming', r:'Distribuida: millones de escrituras por segundo desde dispositivos dispersos geográficamente.'},
      {l:'Banca', r:'Híbrido: núcleo transaccional centralizado por consistencia fuerte, con réplicas distribuidas de solo lectura.'}
    ],
    explain:'La arquitectura correcta depende del volumen, la geografía y qué tan crítica es la consistencia fuerte para ese caso.'},
  {id:'q82', topic:'arquitecturas', type:'vf',
    prompt:'Una base de datos distribuida siempre es más rápida que una centralizada para cualquier consulta.',
    answer:false,
    explain:'No siempre: la coordinación entre nodos (consenso, red) puede añadir latencia; la distribuida ayuda sobre todo con escala, disponibilidad y cercanía geográfica, no garantiza velocidad en toda consulta.'},
  {id:'q83', topic:'arquitecturas', type:'vf',
    prompt:'La escalabilidad vertical consiste en agregar más nodos al clúster.',
    answer:false,
    explain:'Eso es escalabilidad horizontal. La escalabilidad vertical consiste en agregar más CPU, RAM o disco al mismo servidor.'},
  {id:'q84', topic:'arquitecturas', type:'fill',
    prompt:'En una red P2P estructurada, la tabla ___ (sigla de tabla hash distribuida) decide, mediante un hash, en qué nodo concreto se guarda cada dato.',
    answers:['dht'],
    explain:'DHT = tabla hash distribuida. Ejemplos de este tipo de P2P estructurado: Cassandra, IPFS y Chord.'},
  {id:'q85', topic:'arquitecturas', type:'vf',
    prompt:'El paralelismo y la distribución son exactamente lo mismo: ambos responden a la pregunta de dónde vive físicamente cada dato.',
    answer:false,
    explain:'Son ideas relacionadas, no idénticas: la distribución responde dónde vive el dato; el paralelismo responde cómo varios procesadores trabajan sobre él al mismo tiempo (puede ocurrir hasta en un solo servidor con varios núcleos).'},
  {id:'q86', topic:'arquitecturas', type:'fill',
    prompt:'La estrategia de distribución que divide filas de una misma tabla entre nodos distintos, por ejemplo por rango de ID o por región, se llama partición ___ (o sharding).',
    answers:['horizontal'],
    explain:'Se distingue de la partición vertical (que separa columnas) y de la replicación (que copia el mismo dato en varios nodos).'},
  {id:'q87', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada tipo de paralelismo con su definición.',
    pairs:[
      {l:'Paralelismo de datos', r:'El mismo tipo de operación se aplica a distintos fragmentos de datos a la vez.'},
      {l:'Paralelismo de consulta', r:'Una consulta se descompone en subtareas que corren simultáneamente.'},
      {l:'Paralelismo entre transacciones', r:'Varias transacciones independientes se ejecutan a la vez.'}
    ],
    explain:'Ejecutar múltiples operaciones al mismo tiempo usando varios procesadores, núcleos o nodos, en lugar de una tarea tras otra.'},
  {id:'q88', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada estrategia de distribución de datos con su definición.',
    pairs:[
      {l:'Partición horizontal (sharding)', r:'Filas distintas de una misma tabla viven en nodos distintos (ej. por rango de ID o por región).'},
      {l:'Partición vertical', r:'Columnas distintas de una tabla se separan en nodos distintos según el patrón de acceso.'},
      {l:'Replicación', r:'El mismo dato se copia en varios nodos para disponibilidad y lecturas rápidas cerca del usuario.'}
    ],
    explain:'Un mismo sistema puede combinar varias de estas estrategias a la vez.'},
  {id:'q89', topic:'arquitecturas', type:'fill',
    prompt:'Apache Cassandra es una base de datos distribuida, particionada por hash y sin nodo ___.',
    answers:['maestro'],
    explain:'A diferencia de un clúster con nodo maestro, Cassandra reparte la coordinación entre todos los nodos por igual.'},
  {id:'q90', topic:'arquitecturas', type:'vf',
    prompt:'PostgreSQL es la referencia del modelo centralizado clásico, mientras que CockroachDB es un SQL distribuido con consenso Raft.',
    answer:true,
    explain:'Otros motores del mismo repaso: MongoDB (sharded, con réplicas), Google BigQuery (consultas masivamente paralelas) y Apache Spark (paralelismo de datos en clústeres de cómputo).'},
  {id:'q91', topic:'arquitecturas', type:'open',
    prompt:'Menciona una ventaja y una limitación de la arquitectura Peer-to-Peer (P2P), y un ejemplo real donde se use.',
    model:'Ventaja: no tiene un punto único de falla, ya que el sistema sobrevive a la caída de nodos individuales (además escala horizontalmente casi sin límite y a bajo costo). Limitación: la consistencia es eventual, por lo que se puede leer un dato desactualizado, y la seguridad/confianza son difíciles porque los pares son desconocidos. Ejemplos reales: IPFS/Filecoin (almacenamiento por contenido), blockchain (réplica del libro mayor en cada nodo) o Cassandra/Dynamo (anillo de nodos con gossip).'},
  {id:'q92', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada arquitectura de almacenamiento distribuido con su idea central.',
    pairs:[
      {l:'Cliente-Servidor', r:'Un proveedor central posee y administra los datos; muchos clientes los solicitan mediante un protocolo.'},
      {l:'Peer-to-Peer (P2P)', r:'Todos los nodos son iguales: cada uno consume y a la vez provee almacenamiento; los datos se replican entre ellos.'},
      {l:'Clúster', r:'Muchos servidores administrados como una sola unidad; un nodo maestro guarda metadatos y reparte los bloques entre los nodos de datos.'},
      {l:'Multibase / Federación', r:'Varias bases autónomas se consultan como si fueran una sola, sin mover los datos de su sistema de origen.'},
      {l:'Híbrido (local + nube)', r:'Los datos sensibles quedan locales y el cómputo elástico va a la nube; permite "reventar" a la nube en picos (cloud bursting).'}
    ],
    explain:'Cada arquitectura resuelve distinto el mismo problema: dónde viven los datos y quién los administra.'},
  {id:'q93', topic:'arquitecturas', type:'vf',
    prompt:'El modelo cliente-servidor logra consistencia fuerte (ACID) sin necesidad de coordinación distribuida.',
    answer:true,
    explain:'Es una de sus ventajas: al vivir todos los datos en un solo servidor, no hace falta coordinar réplicas ni nodos.'},
  {id:'q94', topic:'arquitecturas', type:'vf',
    prompt:'El modelo cliente-servidor tolera muy bien la distribución geográfica de sus usuarios.',
    answer:false,
    explain:'Es justo una de sus limitaciones: mala tolerancia a la distribución geográfica, además de ser un cuello de botella y un punto único de falla.'},
  {id:'q95', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada "sabor" de red P2P con su ejemplo.',
    pairs:[
      {l:'Puro / no estructurado (búsqueda por inundación)', r:'Gnutella'},
      {l:'Híbrido (con supernodos que mantienen el índice)', r:'BitTorrent con tracker'},
      {l:'Estructurado (DHT, hash consistente)', r:'Cassandra, IPFS, Chord'}
    ],
    explain:'A mayor estructura, más rápida la búsqueda, pero también más dependencia de coordinación o rebalanceo.'},
  {id:'q96', topic:'arquitecturas', type:'fill',
    prompt:'En P2P, el mecanismo por el cual los nodos se cuentan entre sí quién está vivo y qué cambió se llama ___.',
    answers:['gossip'],
    explain:'Junto con la DHT y el direccionamiento por contenido (hash del archivo), es uno de los mecanismos clave del P2P.'},
  {id:'q97', topic:'arquitecturas', type:'fill',
    prompt:'En el modelo de clúster, el nodo ___ guarda los metadatos y decide dónde va cada bloque de datos.',
    answers:['maestro'],
    explain:'Los nodos de datos almacenan los bloques y los replican entre sí; el factor de replicación típico es de 3 copias en nodos distintos.'},
  {id:'q98', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada elección del teorema CAP en un clúster con un ejemplo de motor.',
    pairs:[
      {l:'CP · Consistencia (rechaza la operación antes que devolver un dato viejo)', r:'HBase, MongoDB'},
      {l:'AP · Disponibilidad (siempre responde, aunque la copia no esté al día)', r:'Cassandra, DynamoDB'},
      {l:'CA · Sin partición (solo posible en un nodo o una red perfecta)', r:'PostgreSQL en un servidor'}
    ],
    explain:'Ante una partición de red (P) hay que sacrificar C o A; CA solo es posible cuando no hay partición que enfrentar.'},
  {id:'q99', topic:'arquitecturas', type:'vf',
    prompt:'En un clúster, un factor de replicación típico es guardar 3 copias de cada fragmento en nodos distintos.',
    answer:true,
    explain:'Además, la replicación conviene hacerse en racks distintos, para dar tolerancia a fallos y lecturas más rápidas, a costa de espacio y sincronización.'},
  {id:'q100', topic:'arquitecturas', type:'fill',
    prompt:'Si un clúster usa factor de replicación 3, 10 TB de datos ocupan ___ TB de espacio bruto (sin contar holgura adicional).',
    answers:['30'],
    explain:'Factor de replicación 3 significa que cada dato se guarda en 3 copias distintas: 10 TB x 3 = 30 TB.'},
  {id:'q101', topic:'arquitecturas', type:'fill',
    prompt:'En la federación de bases de datos, la capa de ___ traduce una consulta única en subconsultas y une los resultados, sin que los datos salgan de su sistema de origen.',
    answers:['mediacion'],
    explain:'Existen dos variantes: multibase (fuentes independientes, sin esquema compartido) y federada (con un esquema global unificado).'},
  {id:'q102', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada camino de integración de datos con si copia o no los datos de origen.',
    pairs:[
      {l:'Federación / virtualización', r:'No se copian: se consultan directamente en el origen, en tiempo real.'},
      {l:'ETL a bodega (data warehouse)', r:'Sí: se extraen y transforman antes de cargarse, con datos centralizados y modelados.'},
      {l:'Data lake / lakehouse', r:'Sí: se depositan en crudo, con riesgo de convertirse en un "pantano de datos" si no se organiza bien.'}
    ],
    explain:'Cada camino tiene un buen ajuste distinto: federación para fuentes que no se pueden mover, ETL para reportes estables, data lake para exploración y aprendizaje automático.'},
  {id:'q103', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada modelo de despliegue con su característica clave.',
    pairs:[
      {l:'Local (on-premise)', r:'Hardware propio, control total sobre datos y seguridad física; inversión inicial alta (CAPEX) y capacidad fija.'},
      {l:'Nube (cloud)', r:'Infraestructura rentada a un proveedor; elasticidad y pago por uso (OPEX), sin comprar equipo.'},
      {l:'Híbrido', r:'Combina ambos: datos sensibles locales, cómputo elástico en la nube; permite "reventar" a la nube en picos (cloud bursting).'}
    ],
    explain:'La misma arquitectura lógica puede vivir en estos tres lugares muy distintos.'},
  {id:'q104', topic:'arquitecturas', type:'fill',
    prompt:'La práctica de mover cargas de trabajo puntuales a la nube durante picos de demanda, manteniendo el resto en un centro de datos local, se llama cloud ___.',
    answers:['bursting'],
    explain:'Es propia del modelo híbrido de despliegue: los datos sensibles quedan locales y el cómputo elástico va a la nube.'},
  {id:'q105', topic:'arquitecturas', type:'connect',
    prompt:'Conecta cada criterio para decidir dónde desplegar con lo que evalúa.',
    pairs:[
      {l:'Costo', r:'CAPEX contra OPEX; costo total a 3-5 años, incluyendo salida de datos.'},
      {l:'Latencia', r:'Dónde está el usuario o la máquina que consume; cada salto de red se paga en milisegundos.'},
      {l:'Cumplimiento', r:'Residencia y soberanía del dato: información que legalmente no puede salir del país.'},
      {l:'Elasticidad', r:'Si la carga es estable o tiene picos; los picos justifican la nube.'},
      {l:'Talento y operación', r:'Si la organización tiene el equipo necesario para mantener un clúster propio.'},
      {l:'Continuidad', r:'Plan de respaldo y recuperación; el despliegue híbrido suele nacer justo aquí.'}
    ],
    explain:'Estos seis criterios ayudan a decidir entre local, nube o híbrido para un caso concreto.'},
  {id:'q106', topic:'arquitecturas', type:'open',
    prompt:'Un banco global debe decidir entre un despliegue local, en la nube o híbrido para sus datos de clientes. ¿Qué recomendarías y por qué, considerando cumplimiento normativo y continuidad?',
    model:'Recomendaría un despliegue híbrido: el núcleo transaccional y los datos sensibles de clientes quedan en un centro de datos local o regional, cumpliendo con leyes de residencia y soberanía del dato (información que legalmente no puede salir del país), mientras que el cómputo elástico (análisis, picos de demanda) se apoya en la nube. Esto también da continuidad: un plan de respaldo y recuperación que combine ambos entornos reduce el riesgo de que una sola falla (local o del proveedor de nube) deje al banco sin servicio.'},

  // ---------- Diseño distribuido: requerimientos, CAP y ACID/BASE (20) ----------
  {id:'q107', topic:'diseno', type:'connect',
    prompt:'Conecta cada concepto de diseño distribuido con su definición.',
    pairs:[
      {l:'Consistencia (C)', r:'Todos los nodos responden con el mismo dato.'},
      {l:'Disponibilidad (A)', r:'Cada solicitud recibe una respuesta.'},
      {l:'Tolerancia a partición (P)', r:'El sistema sigue operando aunque la red se corte; en un sistema distribuido real, siempre puede pasar.'},
      {l:'ACID', r:'Prioriza la consistencia; típico de bases relacionales distribuidas (pagos, inventarios, reservas).'},
      {l:'BASE', r:'Prioriza la disponibilidad; típico de bases NoSQL documentales o clave-valor (contadores, feeds, catálogos).'}
    ],
    explain:'C, A y P son las tres letras del teorema CAP; ACID y BASE son las dos filosofías que se acercan, respectivamente, a CP y a AP.'},
  {id:'q108', topic:'diseno', type:'vf',
    prompt:'Un requerimiento funcional describe QUÉ debe hacer el sistema, mientras que uno no funcional describe QUÉ TAN BIEN lo hace (velocidad, disponibilidad, seguridad).',
    answer:true,
    explain:'Ejemplo funcional: "permitir pagar con tarjeta". Ejemplo no funcional: "el pago se procesa en menos de 2 s".'},
  {id:'q109', topic:'diseno', type:'fill',
    prompt:'Un sistema CP prefiere rechazar una operación antes que mostrar un dato desactualizado; un sistema ___ prefiere responder siempre aunque el dato pueda estar un poco desactualizado.',
    answers:['ap'],
    explain:'CP y AP son las dos elecciones posibles ante una partición de red, según el teorema CAP.'},
  {id:'q110', topic:'diseno', type:'vf',
    prompt:'OLTP se caracteriza por muchas filas y agregaciones, mientras que OLAP se caracteriza por pocas filas y consultas muy frecuentes.',
    answer:false,
    explain:'Es al revés: OLTP = pocas filas, muy frecuentes (operar el negocio en tiempo real); OLAP = muchas filas, agregaciones (analizar el negocio en el tiempo).'},
  {id:'q111', topic:'diseno', type:'fill',
    prompt:'En el recordatorio de las propiedades ACID, la letra I corresponde a ___, que garantiza que las transacciones concurrentes no se pisen entre sí.',
    answers:['aislamiento'],
    explain:'A = Atomicidad (todo o nada), C = Consistencia, I = Aislamiento, D = Durabilidad.'},
  {id:'q112', topic:'diseno', type:'open',
    prompt:'Un banco necesita decidir si su sistema de transferencias debe ser CP o AP. Explica qué elegirías y por qué, usando el teorema CAP.',
    model:'Elegiría CP (Consistencia + Partición): en un sistema bancario es preferible rechazar una operación antes que mostrar o aplicar un saldo desactualizado, porque un dato incorrecto en dinero puede causar transferencias duplicadas o saldos inconsistentes. Esto coincide con el perfil ACID (pagos, inventarios, reservas), aunque tenga un costo de latencia y, ante una partición de red, algunas operaciones puedan quedar bloqueadas hasta restaurar la consistencia.'},
  {id:'q113', topic:'diseno', type:'connect',
    prompt:'Conecta cada categoría clave de un sistema distribuido con su definición.',
    pairs:[
      {l:'Disponibilidad', r:'Sigue respondiendo aunque falle un nodo.'},
      {l:'Consistencia', r:'Todos los nodos muestran los mismos datos.'},
      {l:'Latencia', r:'Tiempo de respuesta de una operación.'},
      {l:'Escalabilidad', r:'Capacidad de crecer agregando nodos.'},
      {l:'Tolerancia a fallos', r:'Sobrevive a caídas parciales del sistema.'},
      {l:'Seguridad', r:'Protección de datos y acceso controlado.'}
    ],
    explain:'Estas seis categorías son las más comunes al redactar requerimientos no funcionales de un sistema distribuido.'},
  {id:'q114', topic:'diseno', type:'vf',
    prompt:'Actualizar el inventario cada vez que se vende un producto, en un e-commerce distribuido, es un requerimiento no funcional.',
    answer:false,
    explain:'Es un requerimiento funcional: describe una acción concreta que el sistema debe realizar (junto con registrar un pedido, generar una factura o buscar productos).'},
  {id:'q115', topic:'diseno', type:'fill',
    prompt:'Point query, range query, join y ___: son cuatro formas de consulta que cambian el diseño; la última se resuelve con SELECT cliente_id, SUM(total) FROM pedidos GROUP BY cliente_id.',
    answers:['agregacion'],
    explain:'Cada forma de consulta impone un requisito distinto de diseño: acceso por clave, datos ordenados por rango, cruces costosos entre nodos, o mover datos para agregarlos.'},
  {id:'q116', topic:'diseno', type:'vf',
    prompt:'Una point query, como buscar un pedido por su id (WHERE id = 1042), es ideal para particionar por esa misma clave.',
    answer:true,
    explain:'El acceso por clave se resuelve directamente en el nodo donde vive esa clave, sin cruzar la red.'},
  {id:'q117', topic:'diseno', type:'fill',
    prompt:'Si el 90% de las consultas de un sistema filtran por cliente_id, la decisión de diseño recomendada es particionar por ___.',
    answers:['cliente_id','cliente id'],
    explain:'Regla práctica: el patrón de acceso más frecuente debe poder resolverse sin cruzar la red entre nodos.'},
  {id:'q118', topic:'diseno', type:'fill',
    prompt:'En el caso de la plataforma de streaming de video, el requerimiento no funcional de disponibilidad exige un 99.9%, y el video debe iniciar en menos de ___ segundos.',
    answers:['2'],
    explain:'También debe soportar millones de usuarios simultáneos y tolerar la caída de un centro de datos.'},
  {id:'q119', topic:'diseno', type:'vf',
    prompt:'En el caso de banca móvil, "las transferencias deben confirmarse en menos de 3 segundos" es un requerimiento no funcional.',
    answer:true,
    explain:'Describe qué tan rápido debe comportarse el sistema (una métrica de tiempo), no una acción concreta.'},
  {id:'q120', topic:'diseno', type:'fill',
    prompt:'En el sistema de reservas de vuelos, "reservar un asiento específico" es un requerimiento ___ (funcional o no funcional).',
    answers:['funcional'],
    explain:'Es una acción concreta que el sistema debe permitir; los otros requerimientos del caso son buscar vuelos, consultar historial y generar un reporte de ocupación.'},
  {id:'q121', topic:'diseno', type:'connect',
    prompt:'Conecta cada aspecto de la filosofía ACID/BASE con la opción correcta.',
    pairs:[
      {l:'ACID prioriza', r:'Consistencia'},
      {l:'BASE prioriza', r:'Disponibilidad'},
      {l:'Sistema típico de ACID', r:'Base de datos relacional distribuida'},
      {l:'Sistema típico de BASE', r:'Base de datos NoSQL documental o clave-valor'}
    ],
    explain:'ACID se acerca a CP; BASE se acerca a AP, dentro del espectro del teorema CAP.'},
  {id:'q122', topic:'diseno', type:'fill',
    prompt:'En una transacción distribuida, cada nodo adicional involucrado añade ___ y un punto de falla más.',
    answers:['latencia'],
    explain:'Coordinar que todos los nodos confirmen o cancelen una transacción es más difícil y más lento cuantos más nodos participan.'},
  {id:'q123', topic:'diseno', type:'open',
    prompt:'Explica la diferencia entre OLTP y OLAP con un ejemplo de consulta típica de cada uno.',
    model:'OLTP (transaccional) busca operar el negocio en tiempo real, con consultas de pocas filas pero muy frecuentes, en un diseño normalizado orientado a filas; un ejemplo típico es registrar una venta. OLAP (analítico) busca analizar el negocio a lo largo del tiempo, con consultas de muchas filas y agregaciones, en un diseño desnormalizado orientado a columnas; un ejemplo típico es calcular las ventas totales del trimestre.'},
  {id:'q124', topic:'diseno', type:'vf',
    prompt:'Read-heavy describe sistemas dominados por escrituras, como sensores IoT, mientras que write-heavy describe sistemas dominados por lecturas, como un catálogo de productos.',
    answer:false,
    explain:'Es al revés: read-heavy = dominado por lecturas (catálogo de productos, feed de noticias); write-heavy = dominado por escrituras (registros de log, sensores IoT).'},
  {id:'q125', topic:'diseno', type:'fill',
    prompt:'El diseño típico de un sistema OLAP es desnormalizado y orientado a ___ (filas o columnas).',
    answers:['columnas'],
    explain:'OLTP, en cambio, suele ser normalizado y orientado a filas.'},
  {id:'q126', topic:'diseno', type:'open',
    prompt:'En el sistema de banca móvil del caso de estudio, menciona dos requerimientos funcionales y dos no funcionales distintos.',
    model:'Funcionales: "el sistema debe permitir transferir dinero entre cuentas" y "el sistema debe generar un comprobante en PDF". No funcionales: "las transferencias deben confirmarse en menos de 3 segundos" y "el sistema debe soportar 10 millones de usuarios activos" (también sirven: "debe seguir funcionando si un centro de datos se cae" o "el saldo debe ser el mismo en todos los dispositivos del usuario").'},

  // ---------- Consistencia, concurrencia y 2PC (18) ----------
  {id:'q127', topic:'consistencia', type:'connect',
    prompt:'Conecta cada estrategia o mecanismo de concurrencia/bloqueo con su descripción.',
    pairs:[
      {l:'2PL Distribuido (pesimista)', r:'Pide un candado a todas las réplicas antes de leer o escribir, y no lo suelta hasta terminar.'},
      {l:'Marcas de tiempo (timestamps)', r:'Cada transacción recibe una marca de reloj de Lamport; una operación "vieja" se rechaza y se reintenta.'},
      {l:'Optimista (OCC)', r:'Cada nodo trabaja sobre su copia local y valida justo antes del commit si alguien más modificó ese dato.'},
      {l:'CLM (gestor central de bloqueos)', r:'Un solo servidor decide los candados; si falla, todo el sistema se detiene.'},
      {l:'DLM (gestor distribuido de bloqueos)', r:'Cada nodo guarda una parte de los candados, coordinados por consenso (Raft); si un nodo cae, el resto sigue.'}
    ],
    explain:'Pesimista, por marcas de tiempo y optimista son las tres estrategias para ordenar transacciones que compiten por el mismo dato; CLM y DLM son las dos formas de administrar quién tiene cada candado.'},
  {id:'q128', topic:'consistencia', type:'vf',
    prompt:'El principio PACELC dice que, incluso sin ninguna partición de red, un sistema distribuido debe elegir entre Latencia y Consistencia.',
    answer:true,
    explain:'Esa es la parte "ELC" (Else, operación normal -> elige entre L y C); la parte "PAC" aplica solo cuando sí hay partición (elige entre A y C).'},
  {id:'q129', topic:'consistencia', type:'fill',
    prompt:'En la Confirmación en 2 Fases (2PC), la fase en la que el coordinador pregunta a los participantes si pueden comprometerse, antes de decidir, se llama fase de ___.',
    answers:['prepare'],
    explain:'FASE 1 - PREPARE: ¿pueden comprometerse? FASE 2 - DECISIÓN: si todos votaron "Yes", Commit; basta un solo "No" para Abort en todos.'},
  {id:'q130', topic:'consistencia', type:'vf',
    prompt:'Si el coordinador de un 2PC se cae justo después de recibir todos los votos, los participantes que votaron "Yes" pueden abortar la transacción por su cuenta sin ningún riesgo.',
    answer:false,
    explain:'No pueden: ya prometieron confirmar y tienen los datos bloqueados; no saben qué votó el otro participante ni qué decidió el coordinador antes de caer, así que quedan en un estado de incertidumbre (el sistema deja de responder: es CP en estado puro).'},
  {id:'q131', topic:'consistencia', type:'fill',
    prompt:'El algoritmo que detecta interbloqueos (deadlocks) sin un servidor central, enviando una pequeña "sonda" que viaja de un nodo al siguiente hasta regresar a quien la lanzó, se llama ___.',
    answers:['chandy-misra-haas','chandy misra haas'],
    explain:'Si la sonda regresa a quien la lanzó, el ciclo de espera existe: se aborta una sola transacción (la víctima) y las demás avanzan de inmediato.'},
  {id:'q132', topic:'consistencia', type:'open',
    prompt:'Explica por qué un sistema con Consistencia Fuerte (linearizabilidad) suele tener más latencia que uno con Consistencia Eventual, y da un caso de uso típico para cada uno.',
    model:'La Consistencia Fuerte usa coordinación síncrona: toda lectura debe devolver la escritura más reciente en todo el clúster, lo que requiere bloqueos y consenso antes de confirmar cada operación, y eso cuesta tiempo (viajes de red de ida y vuelta). La Consistencia Eventual usa replicación asíncrona: los nodos responden de inmediato con su copia local y, si no hay nuevas escrituras, van convergiendo con el tiempo, sin bloqueos inmediatos. Caso típico de consistencia fuerte: sistemas transaccionales como banca o mercados de valores. Caso típico de consistencia eventual: redes sociales (contadores de "me gusta"), carritos de compra o microblogging.'},
  {id:'q133', topic:'consistencia', type:'fill',
    prompt:'PostgreSQL, VoltDB, HBase y Bigtable pertenecen al cuadrante de PACELC que prioriza la Consistencia siempre, conocido como ___.',
    answers:['pc/ec','pc ec'],
    explain:'El cuadrante opuesto, PA/EL, prioriza Disponibilidad y Latencia, e incluye motores como Cassandra, DynamoDB y Cosmos DB (por defecto).'},
  {id:'q134', topic:'consistencia', type:'fill',
    prompt:'El principio PACELC combina PAC (si hay Partición, elige entre Disponibilidad y Consistencia) con ELC (en operación normal, elige entre ___ y Consistencia).',
    answers:['latencia'],
    explain:'Abadi argumenta que este trade-off está presente todo el tiempo, incluso sin ninguna caída de red.'},
  {id:'q135', topic:'consistencia', type:'fill',
    prompt:'El cuadrante PA/EL de PACELC prioriza Disponibilidad y Latencia, e incluye motores como Cassandra, DynamoDB y ___ DB (por defecto).',
    answers:['cosmos'],
    explain:'Los sistemas modernos como Cosmos DB o DynamoDB ofrecen controles ajustables para mover la base de datos a lo largo del espectro según la consulta.'},
  {id:'q136', topic:'consistencia', type:'connect',
    prompt:'Conecta cada estrategia de concurrencia con "el precio" que paga a cambio.',
    pairs:[
      {l:'Pesimista (2PL Distribuido)', r:'Cada candado son viajes de red: mucha latencia y riesgo de interbloqueo.'},
      {l:'Marcas de tiempo (timestamps)', r:'Las transacciones lentas se abortan una y otra vez.'},
      {l:'Optimista (OCC)', r:'Si hay muchos conflictos, se tira mucho trabajo ya hecho.'}
    ],
    explain:'Cada estrategia resuelve distinto el mismo problema (dos transacciones que tocan el mismo dato al mismo tiempo) y paga un precio distinto por ello.'},
  {id:'q137', topic:'consistencia', type:'vf',
    prompt:'En el gestor central de bloqueos (CLM), si el servidor único falla, todo el sistema se detiene; en el gestor distribuido (DLM), si un nodo falla, el resto sigue operando.',
    answer:true,
    explain:'CLM es de baja complejidad pero escala poco (se satura); DLM escala mejor pero requiere consenso y acuerdos entre nodos.'},
  {id:'q138', topic:'consistencia', type:'fill',
    prompt:'En un interbloqueo (deadlock), la transacción bloqueada lanza una ___ que viaja de un nodo al siguiente hasta regresar a quien la lanzó.',
    answers:['sonda'],
    explain:'Es la idea central del algoritmo Chandy-Misra-Haas: detectar el ciclo sin necesidad de un servidor central.'},
  {id:'q139', topic:'consistencia', type:'vf',
    prompt:'En el algoritmo Chandy-Misra-Haas, si la sonda regresa a quien la lanzó, se abortan TODAS las transacciones involucradas en el ciclo.',
    answer:false,
    explain:'Se aborta una sola transacción, la "víctima", y las demás avanzan de inmediato.'},
  {id:'q140', topic:'consistencia', type:'fill',
    prompt:'En la Confirmación en 2 Fases (2PC), basta un solo voto "___" de cualquier participante para que la transacción se aborte en todos los nodos.',
    answers:['no'],
    explain:'Si todos votan "Yes", el coordinador manda Commit; con un solo "No", manda Abort para todos.'},
  {id:'q141', topic:'consistencia', type:'vf',
    prompt:'Antes de votar "Yes" en un 2PC, cada participante escribe en su bitácora (WAL) y bloquea los datos, para poder cumplir su promesa aunque se reinicie.',
    answer:true,
    explain:'"Yes" es una promesa: a partir de ese momento el participante ya no puede echarse atrás por su cuenta.'},
  {id:'q142', topic:'consistencia', type:'open',
    prompt:'Explica por qué la falla del coordinador en un 2PC deja al sistema en un estado de "disponibilidad cero" (CP en estado puro), y menciona qué protocolos modernos resuelven este problema.',
    model:'Si el coordinador se cae justo después de recibir los votos pero antes de enviar Commit o Abort, los participantes que ya votaron "Yes" quedan en un estado de incertidumbre: no pueden confirmar ni abortar por su cuenta porque no saben qué votó el otro participante ni qué había decidido el coordinador. Los bloqueos se mantienen indefinidamente y las demás transacciones se forman en fila detrás, así que el sistema deja de responder con tal de no corromper los datos: es un sistema CP en estado puro, pagando el precio en disponibilidad. Por eso los sistemas modernos usan 3PC, Paxos o Raft, que eligen un nuevo coordinador en vez de esperar indefinidamente al que se cayó.'},
  {id:'q143', topic:'consistencia', type:'fill',
    prompt:'La consistencia ___ (Linearizabilidad) usa coordinación síncrona: toda lectura devuelve la escritura más reciente en todo el clúster.',
    answers:['fuerte'],
    explain:'Se opone a la consistencia eventual, que usa replicación asíncrona y prioriza la disponibilidad sobre bloqueos inmediatos.'},
  {id:'q144', topic:'consistencia', type:'vf',
    prompt:'La consistencia eventual usa replicación asíncrona: los nodos convergen con el tiempo si no hay nuevas escrituras.',
    answer:true,
    explain:'A cambio de esa baja latencia y alta disponibilidad, se puede leer un dato desactualizado mientras los nodos convergen.'}
];
